version: '3'

services:
  #api:
  #  depends_on:
  #    - database
  #  build:
  #    context: ./backend
  #    dockerfile: Dockerfile
  #  ports:
  #    - "4000:4000"

  #frontend:
  #  depends_on:
  #    - api
  #  build:
  #    context: ./frontend
  #    dockerfile: Dockerfile
  #    args:
  #      NPM_TOKEN: ${NPM_TOKEN}
  #  ports:
  #    - "8080:8080"

  database:
    build:
      context: .
      dockerfile: database/postgres/Dockerfile
    container_name: repo-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: repo
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d repo"]
      interval: 10s
      timeout: 5s
      retries: 5