version: '3'

services:
  database:
    build:
      context: .
      dockerfile: database/postgres/Dockerfile
    container_name: repo-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: repo
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d repo"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    build:
      context: .
      dockerfile: database/redis/Dockerfile
    container_name: repo-redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5